name: datatest  # Data Testing Tutorial
channels:
- conda-forge
dependencies:
- python>=3.6
- jupyter
- ipykernel
- jupyterlab
- pytest
- pytest-cov
- tinydb
- pyyaml
- pandas-summary
- pandera
- pyjanitor
- pip
- pip:
  - missingno
