name: datatest  # Data Testing Tutorial
channels:
- conda-forge
dependencies:
- python>=3.6
- jupyter
- ipykernel
- jupyterlab
- numpy
- hypothesis
- pytest
- pytest-cov
- tinydb
- pyyaml
- pandas-summary
- pandera
- pyjanitor
- pip
- mypy
- flake8
- pip:
  - missingno
  - mkdocs
  - mkdocs-material
  - mknotebooks
  - pymdown-extensions
