site_name: Software Testing and Data Validation for Data Scientists
theme:
  name: 'material'
  palette:
    primary: 'light blue'
    accent: 'light blue'
    icon:
      logo: 'library_books'
  features:
    - tabs

nav:
  - Home: index.md
  - "Getting Started": 1-getting-setup.ipynb
  - "Prerequisite Knowledge": 2-prerequisite-knowledge.ipynb
  - "Introduction to pytest": 3-pytest-introduction.ipynb
  - "Dataframe validation": 4-data-checks.ipynb

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - mknotebooks:
      execute: true


# Taken from here: https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
markdown_extensions:
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - markdown.extensions.footnotes

extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

repo_name: 'ericmjl/data-testing-tutorial'
repo_url: 'https://github.com/ericmjl/data-testing-tutorial'

extra:
  social:
    - icon: 'material/email'
      link: 'http://www.shortwhale.com/ericmjl'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/ericmjl'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/ericmjl'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://linkedin.com/in/ericmjl'
